### Seed Urls
POST http://localhost:8600/url HTTP/1.1
Content-Type: application/json

["https://books.toscrape.com/"]


### Crawl Perticular Urls
POST http://localhost:8600/crawl/url HTTP/1.1
Content-Type: application/json

["https://www.w3schools.com"]

###
POST http://localhost:8600/crawl/new?lim=100 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8600/crawl/exclusive?lim=100 HTTP/1.1
Content-Type: application/json

["books.toscrape.com"]